### Crear libro
POST http://localhost:5555/books
Content-Type: application/json

{
    "title": "Harry potter 4",
    "author": "J. K. Rowling",
    "publishYear": 2009
}

### Obtener todos los libros
GET http://localhost:5555/books

### Obtener un libro por id
GET http://localhost:5555/books/66d799a7da374ac119c5634c

### Actualizar un libro
PUT http://localhost:5555/books/66d799a7da374ac119c5634c
Content-Type: application/json

{
    "title": "dokodo",
    "author": "Roronoa Zoro",
    "publishYear": 2000
}

### Borrar un libro
DELETE http://localhost:5555/books/66d7a0cb172905e30b9f5870

